# This is a basic workflow to help you get started with Actions

name: Windows Build CI

# Controls when the workflow will run
on: [workflow_dispatch, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.5
      # Runs a set of commands using the runners shell
      - name: script run line haha
        run: |
          haxelib setup ~/haxelib
          haxelib install lime 7.9.0 --quiet
          haxelib install openfl 9.1.0 --quiet
          haxelib install flixel 4.11.0 --quiet
          haxelib install flixel-addons 2.11.0 --quiet
          haxelib install flixel-ui 2.4.0 --quiet
          haxelib install hxcpp 4.2.1 --quiet
          haxelib install newgrounds 1.5.7 --quiet
          haxelib install polymod 1.7.0 --quiet
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib git linc_luajit https://github.com/MRK2009/linc_luajit-0.6.3.git
          haxelib git hxvm-luajit https://github.com/nebulazorua/hxvm-luajit
          haxelib list
          haxelib run lime build windows
          
      - uses: actions/upload-artifact@v4
        with:
          name: Windows Build
          path: export/release/windows/bin
